name: post man task one

on: [push]

jobs:
  runs-on:  ubuntu-latest

  steps:
  -  name: checkout repository
      use: actions/checkout@4

    - name: node installation
        use: actions/setup-node@v3
        with:
          node-version: '14'

    -  name: newman installation
         run: npm install -g newman

    -  name: postman test run
         path: newman run postman_tests\Books.postman_collection.json -e postman_tests\test.postman_environment.json
         



